apiVersion: apps/v1 #replicaset englobando/encapsulando um pod
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias # tem que ser igual ao labels app: portal-noticias. Diz o o kubernetes que o replicaset
    #vai gerenciar esse pod
