apiVersion: v1 
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
          #Se vc quiser ouvir e despachar para uma porta diferente, coloque a tag abaixo:
      #targetPort: 80 #aqui é onde ele vai despachar
      nodePort: 30000 # aqui vc pode definir qual será o ip externo desse svc. Ele pode estar no intervalo de 30000 a 32767
  selector:
    app: portal-noticias