apiVersion: v1 
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  selector:
    app: db-noticias
  ports: 
    - port: 80
      nodePort: 30001
  selector:
    app: sistema-noticias